version=1.0.0-alpha
group=net.hollowed
id=antique
displayName=Antiquities
authors=Main Dev: HollowedWanderer, Physics Sorcerer: Dustley, Code Helper: Mercury, Code Helper: Toady, Code Helper: Yak, Code Helper: The Typhothanian, Original Myriad Armor Model: Semberscythe
description=Adventure awaits...
license=All Rights Reserved

publish.modrinth=antiquities

deps.big_shot=5.0.0-1
deps.modmenu=17.0.0-alpha.1

deps.combat_amenities=3.1.7-1.21.11

org.gradle.jvmargs=-Xmx3G